from django.core.exceptions import ValidationError


class ValidationError(ValidationError):
    pass
